== Daten

Es werden unterschiedliche Arten von Daten unterschieden:

* OpenStreetMap Daten
* Daten für das Routing
* Daten zu Abschnitten und POI

=== OpenStreetMap Daten

Die Applikation benutzt die Routing-Engine von Graphhopper. Hierfür ist es notwendig die passenden OSM-Daten zur Verfügung zu stellen. Sie werden vom Server der Geofabrik bezogen. Das Kopieren erfolgt während des Bauens der Anwendung. Mit dem initialen Aufruf von `mvn clean install` wird ein Datenabzug heruntergeladen, der in der pom.xml definiert ist.

.Beispiel Regierungsbezirk Köln
  <download-osm.fromFile>europe/germany/nordrhein-westfalen/koeln-regbez-latest.osm.pbf</download-osm.fromFile>

Im angegebenen Beispiel werden die Daten für den Regierungsbezirk Köln heruntergeladen

.Beispiel für Hessen
  <download-osm.fromFile>europe/germany/hessen-latest.osm.pbf</download-osm.fromFile>

Im Beispiel für Hessen wird ein Abzug für das Bundesland Hessen heruntergeladen.

Wenn die Routing-Daten aktualisiert werden sollen, kann dies mit Hilfe von `mvn clean install` oder `mvn clean integration-test` erfolgen. `mvn clean` sorgt dabei dafür, dass das Arbeitsverzeichnis gelöscht wird. `mvn install` sorgt unter anderem dafür, dass frische Daten von der Geofabrik heruntergeladen werden.

Auf der Seite _geofabrik.de/europe/germany_ <<geofabrik>> findet sich einen Auflistung, welche Daten von der Geofabrik bezogen werden können.


=== Daten für das Routing

Daten werden in Form von csv-Dateien eingelesen. Diese Dateien werden im `resources` Verzeichnis hinterlegt. Die Daten sollte entsprechend der id aufgebaut sein:

.Dateiname
----
b03-t06.csv
----

Die Struktur besteht aus vier Spalten:

|===
|id|eindeutige id; z.B. 'b03-t06-01-0'
|name|Name des Punktes; 'null' wenn Stützpunkt
|lat|Breitengrad; z.B. '51'
|lng|Längengrad; z.B. '7'
|===

Jeder Datensatz sollte durch die `id` eindeutig identifizierbar sein. Sie sollte im Bezug auf die Kulturdaten folgendermaßen aufgebaut werden:

  <bezirk>-<tour>-<nr>-<punkt>

Wichtig ist hier, dass die Werte innerhalb der ID in der weiteren Verarbeitung verwendet werden. Dafür ist es notwendig, dass die Werte durch `-` von einander getrennt werden.

.Bedeutung der `id`
|===
|bezirk|Bezirk des Kulturpfades: z.B. Lindental: b03
|tour|Nummer der Tour; z.B. Tour 1: t01
|nr|Nummer des Ankerpunktes; p01 für Ankerpunkt, s01 für Stützpunkt
|punkt| 6.1 - Ankerpunkt; 0 - Stützpunkt
|===

.Beispieldatensatz
----
b03-t06-p01-6.1;Pauliplatz;50.93808;6.89794
b03-t06-s01-0;null;50.939027;6.894951
b03-t06-s02-0;null;50.936174;6.894329
b03-t06-p02-6.2;St. Joseph;50.935715;6.898566
b03-t06-s03-0;null;50.935525;6.894479
b03-t06-s04-0;null;50.934525;6.889544
b03-t06-p03-6.3;Am Morsdorfer Hof;50.935508;6.889726
b03-t06-s05-0;null;50.937527;6.883428
b03-t06-s06-0;null;50.934146;6.886303
b03-t06-p04-6.4;Stadtwald;50.934416;6.896775
b03-t06-p05-6.5;Heiligenhäuschen;50.9255224;6.8967102
b03-t06-p06-6.6;St.-Elisabeth-Krankenhaus und -Kirche;50.924175;6.89748
b03-t06-s07-0;null;50.924199;6.899865
b03-t06-p07-6.7;Wohnhäuser von Konrad Adenauer;50.926789;6.899918
b03-t06-s08-0;null;50.928053;6.901571
b03-t06-p08-6.8;Kitschburg;50.926674;6.904746
b03-t06-p09-6.9;Villa Meirowsky;50.932155;6.904891
----

Generell sollen nur Points of Interest miteinander verbunden werden. Dies sind die Ankerpunkte der Route. Es ist aber ggf notwendig Stützpunkte hinzuzufügen, die die Route so anpassen, dass nicht der direkte Weg errechnet wird. Ankerpunkte sind dadurch gekennzeichnet, dass die id mit der Ordnungszahl des Kulturpfades endet, während Stützpunkte dadurch gekennzeichnet sind, dass sie den Prefix mit dem Ankerpunkt teilen, aber die Nummer mit dem 's' verbunden sind.

Weiterhin wird die zweite Spalte, die für das Feld `name` steht, mit dem Wert `null` gefüllt.

.Ankerpunkt und zwei Stützpunkte
----
b03-t06-p01-6.1;Pauliplatz;50.93808;6.89794
b03-t06-s01-0;null;50.939027;6.894951
b03-t06-s02-0;null;50.936174;6.894329
----
