== Daten

Daten werden in Form von csv-Dateien eingelesen. Diese Dateien werden im `resources` Verzeichnis hinterlegt. Die Daten sollte entsprechend der id aufgebaut sein:

.Dateiname
----
b03-t06.csv
----

Die Struktur besteht aus vier Spalten:

|===
|id|eindeutige id; z.B. 'b03-t06-01-0'
|name|Name des Punktes; 'null' wenn Stützpunkt
|lat|Breitengrad; z.B. '51'
|lng|Längengrad; z.B. '7'
|===

Jeder Datensatz sollte durch die `id` eindeutig identifizierbar sein. Sie sollte im Bezug auf die Kulturdaten folgendermaßen aufgebaut werden:

  <bezirk>-<tour>-<nr>-<punkt>

|===
|bezirk|Bezirk des Kulturpfades: z.B. Lindental: b03
|tour|Nummer der Tour; z.B. Tour 1: t01
|nr|Nummer des Ankerpunktes
|punkt| 0 - Ankerpunkt; >0 - Stützpunkt
|===

.Beispieldatensatz
----
b03-t06-01-0;Pauliplatz;50.93808;6.89794
b03-t06-01-1;null;50.939027;6.894951
b03-t06-01-2;null;50.936174;6.894329
b03-t06-02-0;St. Joseph;50.935715;6.898566
b03-t06-02-1;null;50.935525;6.894479
b03-t06-02-2;null;50.934525;6.889544
b03-t06-03-0;Am Morsdorfer Hof;50.935508;6.889726
b03-t06-03-1;null;50.937527;6.883428
b03-t06-03-2;null;50.934146;6.886303
b03-t06-04-0;Stadtwald;50.934416;6.896775
b03-t06-05-0;Heiligenhäuschen;50.9255224;6.8967102
b03-t06-06-0;St.-Elisabeth-Krankenhaus und -Kirche;50.924175;6.89748
b03-t06-06-1;null;50.924199;6.899865
b03-t06-07-0;Wohnhäuser von Konrad Adenauer;50.926789;6.899918
b03-t06-07-1;null;50.928053;6.901571
b03-t06-08-1;Kitschburg;50.926674;6.904746
b03-t06-09-1;Villa Meirowsky;50.932155;6.904891
----

Generell sollen nur Points of Interest miteinander verbunden werden. Dies sind die Ankerpunkte der Route. Es ist aber ggf notwendig Stützpunkte hinzuzufügen, die die Route so anpassen, dass nicht der direkte Weg errechnet wird. Ankerpunkte sind dadurch gekennzeichnet, dass die id auf `-0` endet, während Stützpunkte dadurch gekennzeichnet sind, dass sie den Prefix mit dem Ankerpunkt teilen, die Endzahl aber hochgezählt werden.

Weiterhin wird die zweite Spalte, die für das Feld `name` steht, mit dem Wert `null` gefüllt.

.Ankerpunkt und zwei Stützpunkte
----
b03-t06-01-0;Pauliplatz;50.93808;6.89794
b03-t06-01-1;null;50.939027;6.894951
b03-t06-01-2;null;50.936174;6.894329
----
